version: 2

builds:
  - main: .
    binary: sc
    ldflags:
      - -s -w -X github.com/christopherluey/sc/cmd.Version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "sc_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: christopherluey
    name: sc
